name: slide_up_panel
description: A customizable Flutter widget for creating a draggable and expandable panel that slides up from the bottom of the screen.
version: 1.1.0
homepage: https://github.com/Abdullahzulfiqarxyz/slide_up_panel
repository: https://github.com/Abdullahzulfiqarxyz/slide_up_panel.git


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
